### PR TITLE
bump device crate version, and move examples to the rtfm! macro

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8bb4a94 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8bb4a94 with merge 8bb4a94...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/258808641?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2b7d5c5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2b7d5c5 with merge 2b7d5c5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/258809357?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2b7d5c56b25f4efad6c7c40042f884cbecb47c0b to master...

**Pull request merged**
