### PR TITLE
make the Spi API generic

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 04ecb49 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 04ecb49 with merge 04ecb49...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240571145?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 04ecb49b8495319b87d18f11ca94626481a1f515 to master...

**Pull request merged**
