### PR TITLE
drop the board support crate

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4091474 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4091474eb970b62bee56e538f4d2a9b5336bae6e with merge d43345c0ff92b4a5cdadc984da0930d16241d3ca...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/332827269?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 40d8882 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 40d8882db28d1b53295640bd85709fcde44d5a00 with merge 571d132a9bfcd5c6e41cb9bcdc267019a8aba14e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/332828640?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 571d132a9bfcd5c6e41cb9bcdc267019a8aba14e to master...

**Pull request merged**
