### PR TITLE
add generic Input Capture API

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8791811 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8791811 with merge 8791811...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240466681?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a6cee34 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a6cee34 with merge a6cee34...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240468986?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a6cee343f257e0e83ad7fecfe86ac8793dc6b327 to master...

**Pull request merged**
