### PR TITLE
add PWM + DMA API and WS2812 example

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5111745 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5111745 with merge 5111745...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/244012536?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 51117457500800a514b546791c63dd0ff6075d31 to master...

**Pull request merged**
