### PR TITLE
make Pwm generic

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d52ec99 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d52ec99 with merge d52ec99...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240222306?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d52ec99a4a9956e94ff93411798556e6846d87f6 to master...

**Pull request merged**
