### PR TITLE
faster digital output switching when using the PWM

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c5252ee has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c5252ee with merge c5252ee...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/245224560?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c5252eeef4e9710c199ae96164d37d69e127800d to master...

**Pull request merged**
