### PR TITLE
Serial + DMA and listen APIs

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c089e7e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c089e7e with merge c089e7e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/242690569?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c089e7e526cce4620cf8e1b16d6d62d692e6b814 to master...

**Pull request merged**
