### PR TITLE
integration with `nb` + proper errors

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 92db662 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 92db662 with merge 92db662...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240646989?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4e8dad9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4e8dad9 with merge 4e8dad9...

**Pull request merged**
