### PR TITLE
Fix safe_packed_borrows error

### LINKED ISSUE #31: Build error (packed field borrows)
```text
error: borrow of packed field requires unsafe function or block (error E0133)
   --> src/dma.rs:164:19
    |
164 |             flag: &self.flag,
    |                   ^^^^^^^^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #46043 <https://github.com/rust-lang/rust/issues/46043>
```

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #31

### CODE REVIEW

**Comment by japaric** [comment]
Thanks for the PR. In this case I think it would be better just to remove the `repr(packed)` from the struct. It's not required for this to work; it was just used to work around a bug in rustc that misallocates statically allocated memory (rustc puts variables in .data, instead of in .bss and this wastes flash and makes initialization longer). None of this matter much in any case because the `Buffer` abstraction is going to be phased out in favor of safe `&'static mut` references.

Could you update the PR to drop the `repr(packed)` attribute?

**Comment by lnicola** [comment]
Done.

Not sure if it matters, but the a stripped `release` `blinky` binary was 66 Kb both before and after this change. I'm using `openocd` to flash it and it reports:

```text
before:
wrote 2048 bytes from file target/thumbv7m-none-eabi/release/examples/blinky in 0.177486s (11.268 KiB/s)

after:
wrote 1024 bytes from file target/thumbv7m-none-eabi/release/examples/blinky in 0.099451s (10.055 KiB/s)
```

I'm not sure how relevant is this, or why there's such a large discrepancy between the ELF size and what `openocd` reports.

**Comment by japaric** [comment]
> was 66 Kb

Is that the output of `ls`? That's irrelevant to the actual flash usage. The proper binary size metric to measure is the output of the `size` command:

``` console
$ arm-none-eabi-size target/thumbv7m-none-eabi/release/examples/blinky
   text    data     bss     dec     hex filename
   1024       0       4    1028     404 target/thumbv7m-none-eabi/release/examples/blinky
```

`text` is Flash. `bss` + `data` is static RAM usage (excludes stack and heap usage).

Thanks for the update!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e0294e6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e0294e60f88fd31dca8acd4e614dce81fd284bbf with merge 8bcb4dd5f0557aa158624d50f8bf1a6e1ef0a40b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/319659344?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 43de5ed has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 43de5ed869220dbca817d7555ea0931e95d270d3 with merge 4338e167fc0233d25acd9c65b525e0f864b0a86f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/319664345?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 4338e167fc0233d25acd9c65b525e0f864b0a86f to master...

**Comment by lnicola** [comment]
> The proper binary size metric to measure is the output of the size command

Right, thanks. I had a nagging feeling there was another way to check it 😄 .

**Pull request merged**
