### PR TITLE
extend the Pwm API to partially work with TIM3

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f3f283e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f3f283e with merge f3f283e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240561175?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f3f283e9a80468e22192b413425660ea238b7617 to master...

**Pull request merged**
