### PR TITLE
rename led::Green to led::PC13

### LINKED ISSUE #22: Do not call LED1 `Green`, because it is not necessarily green.
I would recommend not calling the LED1 `Green`, because some boards from Aliexpress come with Red LEDs instead of green ones. Just call it something generic, like `PC13` or `LED1`.

### PR DESCRIPTION
**Pull request by japaric**
closes #22

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8df40ad has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8df40ad with merge 8df40ad...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/277880035?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8df40ad2609ca437b6dbada1978220b7536b47e6 to master...

**Pull request merged**
