### PR TITLE
Fix PWM generation for TIM1

### PR DESCRIPTION
**Pull request by nikhilkalige**
`MOE` bit in `BDTR` register needs to be set.

### CODE REVIEW

**Comment by japaric** [comment]
I don't think I'll be able to test this on hardware any time soon but I'll trust you on this one :-)

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e50ae4c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e50ae4c with merge 8aecbea...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/277744252?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8aecbea402a829c03001dbedf24394d5e20c7def to master...

**Pull request merged**
