### PR TITLE
LED should be a `const` not a type alias

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 506c946 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 506c946 with merge 506c946...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/282244896?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 506c946e839ff7d167e8a0788e4c5b5c29a3f6b3 to master...

**Pull request merged**
