### PR TITLE
cortex-m-hal was renamed to embedded-hal

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8a81079 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8a81079 with merge 8a81079...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/241632676?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8a810794ab0ce0050036b89a58ba01b129d7be7b to master...

**Pull request merged**
