### PR TITLE
switch to the new svd2rust model

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 077cfe9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 077cfe99c56ebe317d35718748e78d43b936175a with merge a90047b676c1c0ea537c1d27517e5fda17a42600...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/332794752?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a90047b676c1c0ea537c1d27517e5fda17a42600 to master...

**Pull request merged**
