### PR TITLE
AsRef/AsMut -> Unsize

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 254c5df has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 254c5df with merge 254c5df...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/244020248?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 254c5df99eac50967b30e2369cef41b5275c57ff to master...

**Pull request merged**
