### PR TITLE
integrate with cortex-m-hal

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 497c548 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 497c548 with merge 497c548...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/241357043?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 497c5487a345645f84536d8c08eeca9650767d36 to master...

**Pull request merged**
