### PR TITLE
generic Serial + CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e268df7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e268df7 with merge e268df7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240205229?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a2ead04 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a2ead04 with merge a2ead04...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240205641?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c2f399c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c2f399c with merge c2f399c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240205985?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ba15af1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ba15af1 with merge ba15af1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240207685?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ba15af18d9052026f7be71d82882b60b2e8030bb to master...

**Pull request merged**
