### PR TITLE
extend the Capture API to partially work with TIM3

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 463a7de has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 463a7de with merge 463a7de...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240550172?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 463a7dee653c0fdbcb325cefddf56e887e5e0867 to master...

**Pull request merged**
