### PR TITLE
make the `Time` API generic

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit eb57645 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit eb57645 with merge eb57645...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240535889?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6478a77 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6478a77 with merge 6478a77...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/blue-pill/builds/240542563?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6478a7745fcf8e77da78371e3a804470975fb6be to master...

**Pull request merged**
